include: package:pedantic_mono/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/l10n/messages_*.dart
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
